server.port=8081

spring.application.name=account-service

spring.datasource.url=jdbc:postgresql://localhost:5433/fintrack
spring.datasource.username=fintrack
spring.datasource.password=fintrack
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=account_service
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.jackson.serialization.write-dates-as-timestamps=false
